export const FAKE_POPULARS = [
  {
    backdrop_path: '/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg',
    first_air_date: '2022-11-23',
    genre_ids: [10765, 9648, 35],
    id: 119051,
    name: 'Wednesday',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Wednesday',
    overview:
      'Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.',
    popularity: 10410.315,
    poster_path: '/jeGtaMwGxPmQN5xM4ClnwPQcNQz.jpg',
    vote_average: 8.8,
    vote_count: 1721,
  },
]

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: '/wNKwOtq27yfN13SKKV07NwkpBA3.jpg',
    id: 80752,
    name: 'See',
    original_language: 'en',
    original_name: 'See',
    overview:
      'A virus has decimated humankind. Those who survived emerged blind. Centuries later when twins are born with the mythic ability to see, their father must protect his tribe against a threatened queen.',
    poster_path: '/lKDIhc9FQibDiBQ57n3ELfZCyZg.jpg',
    media_type: 'tv',
    genre_ids: [18, 10765, 10759],
    popularity: 181.391,
    first_air_date: '2019-11-01',
    vote_average: 8.236,
    vote_count: 1908,
    origin_country: ['CA'],
  },
  {
    adult: false,
    backdrop_path: '/suopoADq0k8YZr4dQXcU6pToj6s.jpg',
    id: 1399,
    name: 'Game of Thrones',
    original_language: 'en',
    original_name: 'Game of Thrones',
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    poster_path: '/7WUHnWGx5OO145IRxPDUkQSh4C7.jpg',
    media_type: 'tv',
    genre_ids: [10765, 18, 10759],
    popularity: 555.32,
    first_air_date: '2011-04-17',
    vote_average: 8.431,
    vote_count: 19895,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
    id: 66732,
    name: 'Stranger Things',
    original_language: 'en',
    original_name: 'Stranger Things',
    overview:
      'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
    poster_path: '/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    media_type: 'tv',
    genre_ids: [18, 10765, 9648],
    popularity: 334.769,
    first_air_date: '2016-07-15',
    vote_average: 8.642,
    vote_count: 14474,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg',
    id: 94605,
    name: 'Arcane',
    original_language: 'en',
    original_name: 'Arcane',
    overview:
      'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.',
    poster_path: '/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg',
    media_type: 'tv',
    genre_ids: [16, 10765, 10759, 18],
    popularity: 95.582,
    first_air_date: '2021-11-06',
    vote_average: 8.751,
    vote_count: 2726,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/un5r5MwwzEBwN1XEpPzeDoeu6fq.jpg',
    id: 2490,
    name: 'The IT Crowd',
    original_language: 'en',
    original_name: 'The IT Crowd',
    overview:
      'Two I.T. nerds and their clueless female manager, who work in the basement of a very successful company. When they are called on for help, they are never treated with any respect at all.',
    poster_path: '/qZXkBoOUYzvKI4UCMzDQ5kqWHjh.jpg',
    media_type: 'tv',
    genre_ids: [35],
    popularity: 38.929,
    first_air_date: '2006-02-03',
    vote_average: 8.115,
    vote_count: 1022,
    origin_country: ['GB'],
  },
  {
    adult: false,
    backdrop_path: '/uGy4DCmM33I7l86W7iCskNkvmLD.jpg',
    id: 60625,
    name: 'Rick and Morty',
    original_language: 'en',
    original_name: 'Rick and Morty',
    overview:
      "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
    poster_path: '/cvhNj9eoRBe5SxjCbQTkh05UP5K.jpg',
    media_type: 'tv',
    genre_ids: [16, 35, 10765, 10759],
    popularity: 873.87,
    first_air_date: '2013-12-02',
    vote_average: 8.7,
    vote_count: 7478,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/a906PH7CDmSOdS7kmnAgdWk5mhv.jpg',
    id: 67744,
    name: 'Mindhunter',
    original_language: 'en',
    original_name: 'Mindhunter',
    overview:
      "An agent in the FBI's Elite Serial Crime Unit develops profiling techniques as he pursues notorious serial killers and rapists.",
    poster_path: '/fbKE87mojpIETWepSbD5Qt741fp.jpg',
    media_type: 'tv',
    genre_ids: [18, 80],
    popularity: 51.569,
    first_air_date: '2017-10-13',
    vote_average: 8.045,
    vote_count: 1806,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/zaulpwl355dlKkvtAiSBE5LaoWA.jpg',
    id: 1402,
    name: 'The Walking Dead',
    original_language: 'en',
    original_name: 'The Walking Dead',
    overview:
      "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
    poster_path: '/xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg',
    media_type: 'tv',
    genre_ids: [10759, 18, 10765],
    popularity: 750.574,
    first_air_date: '2010-10-31',
    vote_average: 8.112,
    vote_count: 14162,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/rX5hvSRB2k4YoIvRg6Zky52rWk0.jpg',
    id: 63247,
    name: 'Westworld',
    original_language: 'en',
    original_name: 'Westworld',
    overview:
      'A dark odyssey about the dawn of artificial consciousness and the evolution of sin. Set at the intersection of the near future and the reimagined past, it explores a world in which every human appetite, no matter how noble or depraved, can be indulged.',
    poster_path: '/8MfgyFHf7XEboZJPZXCIDqqiz6e.jpg',
    media_type: 'tv',
    genre_ids: [10765, 37],
    popularity: 121.165,
    first_air_date: '2016-10-02',
    vote_average: 8.107,
    vote_count: 4553,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/foDTy1NcfTzKnzXzgTp1FBu653F.jpg',
    id: 615,
    name: 'Futurama',
    original_language: 'en',
    original_name: 'Futurama',
    overview:
      'The adventures of a late-20th-century New York City pizza delivery boy, Philip J. Fry, who, after being unwittingly cryogenically frozen for one thousand years, finds employment at Planet Express, an interplanetary delivery company in the retro-futuristic 31st century.',
    poster_path: '/k5e8kAq9jpaSmgvFM10su5LXGFR.jpg',
    media_type: 'tv',
    genre_ids: [16, 10759, 35, 10765],
    popularity: 136.611,
    first_air_date: '1999-03-28',
    vote_average: 8.391,
    vote_count: 2499,
    origin_country: ['US'],
  },
]
